Реализованы все требования ТЗ, проведены тесты
Scutc/java-filmorate pull request #1
Opened 2022-09-19 15:34 UTC by Scutc

2022-09-20 16:23 UTC, krylov-sergey-sergeevich requested changes
Привет, надо дописать тесты и учесть небольшие замечания - в целом хорошо

2022-09-20 16:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @RequestBody Film film) throws ValidationException {
createFilm более кхм подходит по названию

2022-09-20 16:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean filmValidation(Film film) {
лайк за то что вынесено в отдельный метод, только лучше название методов делать глагол+существительное т.е validationFilm

2022-09-20 16:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Map<Integer, User> users = new HashMap<>();
Модификаторы доступа

2022-09-20 16:23 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User addUser(@Valid @RequestBody User user) throws ValidationException {
createUser

2022-09-21 11:21 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
добавил

2022-09-21 11:22 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film addFilm(@Valid @RequestBody Film film) throws ValidationException {
поправил

2022-09-21 11:25 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean filmValidation(Film film) {
поправил

2022-09-21 11:25 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    Map<Integer, User> users = new HashMap<>();
спасибо, поправил! что-то сбойнуло у меня с модификаторами в этот раз :)

2022-09-21 11:48 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
добавил дополнительные аннотации

2022-09-21 11:49 UTC, Scutc commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Это я облажался. Как-то пропустил пункт ТЗ про необходимость покрытия тестами, и сам инициативу не проявил :) Сейчас добавил

2022-09-21 14:05 UTC, Scutc commented
Добавил автотесты, но к сожалению не разобрался, как сделать правильно и протестировать спринг приложение и проверить работу контроллеров с аннотацией @Valid.  Наставник давал пример как это можно сделать с помощью объектов mok, но я не до конца разобрался, а учитывая, что аннотация @Valid была дополнительным заданием ТЗ и тема с МОК-тестированием нам еще только предстоит в будущем, пока решил сделать по-старинке. Т.е. тестирую валидацию с помощью кастомного метода валидации.

2022-09-21 18:59 UTC, krylov-sergey-sergeevich approved these changes
Все хорошо, отписал мелкие замечания в целом - зачет!

Удачи с следующими заданиями =)

2022-09-21 18:59 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTests.java
> +    void validationFilmTest() throws ValidationException {
Надо разбить тест на более маленькие тесты и дать им точечные названия

2022-09-21 18:59 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    void validationUserTest() throws ValidationException {
Тоже нужно разбить тест на небольшие и дать названия которые символизируют кейс проверяемый

2022-09-22 11:02 UTC, merged