Add friends likes
Scutc/java-filmorate pull request #2
Opened 2022-10-03 18:42 UTC by Scutc

Привет! Буду признателен за глубокий разбор, времени до конца спринта еще достаточно, можно успеть что-то и улучшить :)

2022-10-04 13:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if (user.getFriends() == null) {
Можем по умолчанию сделаем чтобы всегда было не null?

2022-10-04 13:36 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        user.getFriends().add(friendId);
это плохая практика, лучше сделать отдельный метод addUser или addFriends и внутри них уже делать добавление в список

2022-10-04 13:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +
пустые строчки лучше не внизу, а между методами)

2022-10-04 13:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +@Slf4j
поменять местами аннотации

2022-10-04 13:37 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Map<Long, Film> films = new HashMap<>();
final?

2022-10-04 13:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
Логи как то выборочно написаны, давай системно везде

2022-10-04 13:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public InMemoryUserStorage() {
зачем конструктор если это по идее можно сразу определить

2022-10-04 13:39 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +@Slf4j
поменять местами аннотации

2022-10-04 13:39 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public void deleteUser(User user) {
пусто - это грустно

2022-10-04 13:39 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return null;
так и задумано?)

2022-10-05 08:34 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Реализовал. Не знаю насколько близко к эталонному решению, но вроде работает :)

2022-10-05 08:36 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new FilmNotFoundException("Фильм не найден. Данные не обновлены!");
Добавил айдишники здесь и везде где необходимо

2022-10-05 08:36 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new FilmNotFoundException("Фильм с таким ID не найден");
поправил

2022-10-05 08:36 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
перенес и дописал все логи на уровне контроллеров

2022-10-05 08:36 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +@Slf4j
сделано

2022-10-05 08:37 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public void deleteUser(User user) {
пропустил :( Сейчас реализовал

2022-10-05 08:37 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return null;
Нет конечно :) Недоработочка... Поправил

2022-10-05 09:01 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmStorage filmStorage, FilmService filmService) {
Передал на аннотацию @AllArgsConstructor. Не сделал это сразу, т.к. считал, что мне нужно куда-то прикрутить спринговую аннотацию @Autowired. А оказалось, что она необязательная.

2022-10-05 09:01 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserStorage userStorage, UserService userService) {
готово

2022-10-05 09:16 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public InMemoryUserStorage() {
Я (видимо ошибочно :) ) полагал, что инициализация через конструктор это что-то типа хорошего тона :) Ну буду знать теперь. Переделал

2022-10-05 17:53 UTC, Scutc commented
Привет! Поправил все по замечаниям кроме реализации тестов. Пока отправляю на ревью без дополнительных тестов (они вроде как по ТЗ не требовались), буду делать параллельно, чтобы не терять время. Вдруг у тебя еще какие-то замечания появятся.

2022-10-05 19:51 UTC, krylov-sergey-sergeevich requested changes
Привет, ощущение что учтено часть комментариев. Плюс сильно едет стиль - поэтому как задача со звездочкой прикрутить автоматическую проверку стиля и редактирование его.

Так-же если есть желание тесты дописать + поправить что в комментариях указано.

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Проверьте корректность введенных данных", "POST/films");
Так путь передавать можно, но также можно и достать из самого запроса в ErrorHandler, но ладно это на будущее оставим

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Проверьте корректность введенных данных", "POST/films");
https://habr.com/ru/post/528116/

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
Проверка на != null по ощущению часто дублируется

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
Не докинули =(

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private @NonNull long id;
Тут нет правки =(

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        user.getFriends().add(friendId);
Тут не проработано вроде как

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        user.getFriends().remove(friendId);
Тут не проработано вроде как

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +
Тут не проработано вроде как

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
Лишние пустые строки

2022-10-05 19:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Map<Long, Film> films = new HashMap<>();
Тут не учтено вроде как

2022-10-07 06:41 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
Я что-то не понимаю :( Какой правки ты ждешь? может я что-то в предыдущих комментариях упустил, но вот вообще не понимаю :((( Что я не докинул и не проработал?  С пустыми строками ок, поправил

2022-10-07 06:41 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +public class InMemoryFilmStorage implements FilmStorage{
удалил

2022-10-07 15:04 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Проверьте корректность введенных данных", "POST/films");
Передалал, благодарю за настойчивость :) Получилось гораздо лучше без костылей. Правда, я не нашел в предложенной статье способа отображения сообщения пользователю в том виде, как я хотел. Но удалось найти иной способ через HttpServletRequest. В любом случае решение гораздо менее костыльное и гибкое, чем исходное предложенное мной.

2022-10-07 18:44 UTC, Scutc commented
Привет! К сожалению не понял о чем комментарии типа "не докинули", "не проработано", "не учтено". Выпало прямо из контекста и как не пытался понять, не удалось :( Причем эти замечания почему-то не получается обсудить здесь, они без возможности комментирования. 
По автоматической проверке code style не уверен, что верно понял конечную цель. Но я действительно пренебрегал инструментами автоматической проверки. Сейчас чуть подкрутил настройки IDEA и на всех классах применил проверку код стайла. Если то то, что ожидалось, то, надеюсь, сейчас и далее станет получше. Возьму себе за правило.

2022-10-07 18:46 UTC, Scutc commented
P.S. уже после того, как написал свой комментарий предыдущей увидел, что был отдельный линк для загрузки скрытых комментариев. Я их поэтому и пропустил в прошлый раз - просто не увидел :) Пойду разбираться дальше

2022-10-07 18:48 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +public class FilmNotFoundException extends RuntimeException{
В текущий итерации я чуть переработал сами исключения, убрав из них несвоейственный атрибут с сохранением пути запроса. Буду признателен если задашь направление, в котором нужно перерабатывать систему

2022-10-07 18:52 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
Теперь докинули :) @Getter
@RequiredArgsConstructor

2022-10-07 19:07 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private @NonNull long id;
Поправил теперь, в прошлый раз не увидел этот и часть других комментариев :(

2022-10-07 19:37 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage userStorage) {
убрал

2022-10-07 19:39 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if (user.getFriends() == null) {
сделал в момент создания/обновления

2022-10-07 19:43 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if (user.getFriends() == null) {
не не уровне свойств объекта, а просто как инициализацию этого поля в случае, если там ничего нет. Делаю это, т.к объект Юзер приходит извне и список может быть пустой (собственно в тестах постмана список и не приходит)

2022-10-07 20:00 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        if (user == null || friend == null) {
это ушло

2022-10-07 20:07 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        if (film == null) {
Вынес в отдельные методы типа filmCleaningUp

2022-10-07 20:11 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +@Slf4j
done

2022-10-07 20:12 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Map<Long, Film> films = new HashMap<>();
done

2022-10-07 20:26 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        user.getFriends().add(friendId);
теперь ок

2022-10-07 20:27 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        user.getFriends().remove(friendId);
теперь ок

2022-10-07 20:39 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
пока оставил так, сходу не понимаю что здесь качественно можно оптимизировать, т.к. не проверять нельзя - запросы приходят извне и в них что угодно может быть

2022-10-07 20:39 UTC, Scutc commented
Так, ну надеюсь теперь ничего не упустил..

2022-10-09 08:29 UTC, krylov-sergey-sergeevich approved these changes
Привет, выглядит достойно - зачет. Код стайл почти везде корректен уже хорошо, написал пару замечаний небольших их к следующей дз думаю можно будет учесть/поправить

2022-10-09 08:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +ErrorHandler {
Куда то съехало название класса

2022-10-09 08:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    public UserService(UserStorage userStorage) {
Давай добавим аннотацию чтобы убрать конструктор

2022-10-09 08:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        Set<Long> commonFriendsIds;
Возможно эту и следующую строку имеют в одну схлопнуть

2022-10-09 08:29 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTests.java
> +    void modelInitialization() {
Как задание "на дом" почитай про Mock bean и библиотеку Mockito

2022-10-22 16:53 UTC, merged