Add database
Scutc/java-filmorate pull request #3
Opened 2022-11-05 20:11 UTC by Scutc

2022-11-07 06:57 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом хорошо есть пару моментов которые давай обсудим и в следующий раз будет зачет. 
Еще хотел спросить на счет тестов, по сути были переделаны тесты с in memory хранения на бд. Выходит что теперь in memory не будут покрыты тестами, может стоило рядом просто еще файлы создать и в них протестировать? Или как нибудь отнаследоваться, вообщем есть ощущение что часть функционала теперь без тестов.

2022-11-07 06:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserDbService.java
> +    private final int FRIENDSHIP_APPROVED = 1;
Можно static докинуть

2022-11-07 06:57 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    /*Здесь пришлось вернуть конструктор несмотря на Lombok, т.к. пока не понял, как инициализировать переменную
Тоже неплохой подход, рекомендую еще почитать о GeneratedKeyHolder

2022-11-07 19:09 UTC, Scutc commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ =@Autowired)
Привет! Нам в ТЗ предложена эта аннотация для интеграционных тестов. Если ее не добавлять, то тесты падают, т.к. не инжектится объект jdbcTemplate

2022-11-07 19:11 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmDbService.java
> +@Qualifier("filmDbService")
да, здесь лишнее, случайно залетело.

2022-11-07 19:16 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +public class MpaDbStorage {
готово

2022-11-07 19:21 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +public class GenreDbStorage {
готово

2022-11-07 20:02 UTC, Scutc commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    /*Здесь пришлось вернуть конструктор несмотря на Lombok, т.к. пока не понял, как инициализировать переменную
Спасибо, ознакомился! Я генерацию айдишника оставил на уровне приложения, не выносил в базу, т.к. как-то больше контроля с моей точки зрения. Но на будущее буду иметь ввиду.

2022-11-07 20:06 UTC, Scutc commented
Спасибо за ревью! Да, действительно, тесты переделал под новую реализацию с БД. Нам тут наставник в слаке вообще говорит о том, что про старую реализацию InMemory можно забыть вплоть до того, что можно уничтожить соответствующие ей классы. Поэтому я с твоего позволения сейчас не буду тратить время на возвращение старых тестов. Но на будущее обязательно учту рекомендацию на этот счет. Действительно, можно было отнаследоваться от старых классов, т.к. изменения в тестах оказались минимальными

2022-11-08 06:13 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - отлично, зачет!

2022-11-08 16:04 UTC, merged